### ISSUE TITLE
Tanh transformation

### ISSUE THREAD

**Issue by yardenas** [JiaYaobo/fenbux#13]
Is there any plan to include this soon? Seems quite useful to RL people.

I can help with making the PR with some guidance

**Comment by JiaYaobo** [comment]
@yardenas thanks for your question!
It seems like you need a `tanh` bijector like https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/Tanh, for now `fenbux` doesn't have a general `bijector` module (with only loc scale transformation in fenbux/univariate), and I think these transformations including `tanh`, `exp` etc. should be placed in a specific `bijector` module, I think it's easy to quickly provide a `bijector` api draft (Actually I made this several months ago), though maybe not cover all feaures about bijectors (like inverse of a bijector or inverse jacobian), I will still cover common apis like `logpdf` and `rand`, if you think it's acceptable, I will create the bijector apis soon.
Interface will be like
```python
from fenbux.bijector import Tanh
from fenbux.univariate.continuous import Normal
import fenbux as fbx

d = Normal(0 ,1)
bij = Tanh()
tanh_normal = fbx.transform(d, bij)

fbx.logpdf(tanh_normal, 0.)
```
WDYT?

**Comment by yardenas** [comment]
@JiaYaobo that looks awesome!

I really like the simplicity of the api :)

Is there a (concise) way for me to help pushing this?

**Comment by JiaYaobo** [comment]
@yardenas Hi, I just made a pr as a draft for bijectors https://github.com/JiaYaobo/fenbux/commit/2d7456960d59b06fb30db03f6ac077cffeca4c71, you can fork the `main` branch to your own repo, and modify it!

As you want to add `Tanh` bijector. I recommend refer to `fenbux/bijector/logit`

You need to register several methods for `Tanh`

* inverse, you can use `Inverse` bijector like what we do in `Logit`
* evaluate, simply the function of `tanh` call on input `x`
* ladj, log_abs_det_jac function, you can refer to tensorflow_probability etc.
* value_and_ladj, simple combination of evalute and ladj

then in `fenbux/bijector/__init__.py` add your `Tanh` bijector.

For tests,
* Add a test in `tests/bijector/test_tanh.py`, you can refer to `test_exp_log.py`
* Add a test in `tests/bijector/test_logpdf.py`, you can refer to the existing tests.

After all, free feel to make a pull request, code style is not a big problem

**Comment by JiaYaobo** [comment]
@yardenas I've added `Tanh` bijector to main, you can try it out! Closing the isssue!
Example usage:
```python
from fenbux.bijector import Tanh, transform
from fenbux.univariate.continuous import Normal
import fenbux as fbx

d = Normal(0 ,1)
bij = Tanh()
tanh_normal = transform(d, bij)
fbx.logpdf(tanh_normal, 0.)
```

**Comment by yardenas** [comment]
Thank you 🤩
